### ISSUE TITLE
spleeter's separator needs a filepath, not buffer

### ISSUE THREAD

**Issue by rhroberts** [rhroberts/spleeterweb#1]
I'd prefer not to save anything to disk. Is there a workaround here?

```python
Traceback (most recent call last):
  File "/home/rusty/.cache/pypoetry/virtualenvs/spleeterweb-BNGiXFUJ-py3.6/lib/python3.6/site-packages/werkzeug/datastructures.py", line 3089, in __getattr__
  return getattr(self.stream, name)
  AttributeError: 'SpooledTemporaryFile' object has no attribute 'decode'

                   During handling of the above exception, another exception occurred:

                   Traceback (most recent call last):
  File "/home/rusty/.cache/pypoetry/virtualenvs/spleeterweb-BNGiXFUJ-py3.6/lib/python3.6/site-packages/flask/app.py", line 2464, in __call__
  return self.wsgi_app(environ, start_response)
  File "/home/rusty/.cache/pypoetry/virtualenvs/spleeterweb-BNGiXFUJ-py3.6/lib/python3.6/site-packages/flask/app.py", line 2450, in wsgi_app
  response = self.handle_exception(e)
  File "/home/rusty/.cache/pypoetry/virtualenvs/spleeterweb-BNGiXFUJ-py3.6/lib/python3.6/site-packages/flask/app.py", line 1867, in handle_exception
  reraise(exc_type, exc_value, tb)
  File "/home/rusty/.cache/pypoetry/virtualenvs/spleeterweb-BNGiXFUJ-py3.6/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
  raise value
  File "/home/rusty/.cache/pypoetry/virtualenvs/spleeterweb-BNGiXFUJ-py3.6/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
  response = self.full_dispatch_request()
  File "/home/rusty/.cache/pypoetry/virtualenvs/spleeterweb-BNGiXFUJ-py3.6/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
  rv = self.handle_user_exception(e)
  File "/home/rusty/.cache/pypoetry/virtualenvs/spleeterweb-BNGiXFUJ-py3.6/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
  reraise(exc_type, exc_value, tb)
  File "/home/rusty/.cache/pypoetry/virtualenvs/spleeterweb-BNGiXFUJ-py3.6/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
  raise value
  File "/home/rusty/.cache/pypoetry/virtualenvs/spleeterweb-BNGiXFUJ-py3.6/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
  rv = self.dispatch_request()
  File "/home/rusty/.cache/pypoetry/virtualenvs/spleeterweb-BNGiXFUJ-py3.6/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
  return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/rusty/Code/spleeterweb/spleeterweb/app.py", line 34, in application_root
  result = spleeter.split(input_file, "2stem")
  File "/home/rusty/Code/spleeterweb/spleeterweb/spleeter.py", line 11, in split
  waveform, _ = audio_loader.load(input_file, sample_rate=sample_rate)
  File "/home/rusty/.cache/pypoetry/virtualenvs/spleeterweb-BNGiXFUJ-py3.6/lib/python3.6/site-packages/spleeter/audio/ffmpeg.py", line 99, in load
  path = path.decode()
  File "/home/rusty/.cache/pypoetry/virtualenvs/spleeterweb-BNGiXFUJ-py3.6/lib/python3.6/site-packages/werkzeug/datastructures.py", line 3095, in __getattr__
  return getattr(self.stream._file, name)
  AttributeError: '_io.BufferedRandom' object has no attribute 'decode'
```

**Comment by rhroberts** [comment]
going the `tempfile` route
